#ifndef PARSER_H
#define PARSER_H

#include "lexer.h"

enum node_type {
	NODE_PROGRAM,
	NODE_FUNCTION,
	NODE_GLOBAL,
	NODE_RETURN,
	NODE_NUMBER,
	NODE_UNARY,
	NODE_BINARY,
	NODE_DECLARATION,
	NODE_ASSIGN,
	NODE_VAR,
	NODE_COMPOUND,
	NODE_IF,
	NODE_WHILE,
	NODE_FOR,
	NODE_BREAK,
	NODE_CONTINUE,
	NODE_CALL,
	NODE_PREFIX_INC,
	NODE_PREFIX_DEC,
	NODE_POSTFIX_INC,
	NODE_POSTFIX_DEC,
	NODE_ADDR_OF,
	NODE_DEREF,
	NODE_DEREF_ASSIGN,
	NODE_PTR_DECLARATION,
	NODE_TERNARY,
	NODE_ARRAY_DECL,
	NODE_CHAR_DECLARATION,
	NODE_CHAR_PTR_DECLARATION,
	NODE_CHAR_ARRAY_DECL,
	NODE_STRING,
	NODE_STRUCT_DEF,
	NODE_STRUCT_DECL,
	NODE_STRUCT_PTR_DECL,
	NODE_MEMBER,
	NODE_MEMBER_ASSIGN,
	NODE_PTR_MEMBER,
	NODE_PTR_MEMBER_ASSIGN,
	NODE_SWITCH,
	NODE_CASE,
	NODE_DEFAULT,
	NODE_DO_WHILE,
	NODE_GLOBAL_PTR,
	NODE_GLOBAL_CHAR_PTR,
	NODE_GLOBAL_ARRAY,
	NODE_GLOBAL_CHAR_ARRAY,
	NODE_PROTO,
	NODE_UNSIGNED_DECLARATION,
	NODE_UNSIGNED_CHAR_DECLARATION,
	NODE_LONG_DECLARATION,
	NODE_STRUCT_RET,
	NODE_STRUCT_VAL_PARAM,
	NODE_CAST,
	NODE_FPTR_DECLARATION,
	NODE_SIZEOF_STRUCT,
	NODE_STRUCT_ARRAY_DECL,
	NODE_GLOBAL_STRUCT,
	NODE_GLOBAL_STRUCT_PTR,
	NODE_GLOBAL_STRUCT_ARRAY,
	NODE_PTR_ARRAY_DECL,
	NODE_CHAR_PTR_ARRAY_DECL,
	NODE_GLOBAL_PTR_ARRAY,
	NODE_GLOBAL_CHAR_PTR_ARRAY,
	NODE_VARARG,
	NODE_VA_LIST_DECL,
	NODE_VA_START,
	NODE_VA_ARG,
	NODE_VA_END,
	NODE_PTR_RET,
};

struct ast_node {
	enum node_type type;
	char *value;
	struct ast_node **children;
	int child_count;
};

struct ast_node *parse(struct token *tokens, int token_count);
void free_ast(struct ast_node *node);

# endif
